### PR TITLE
update new feature

### PR DESCRIPTION
**Pull request by chris-chris**
Freaking new feature!
Coming soon!!!!
I stayed all the night for 3 days haha

### CODE REVIEW

**Comment by future-tech-holic** [comment]
Oh, you did a great job! Thank you for your passion

**Comment by chris-chris** [comment]
Oh, I can't wait to implement the next feature!
This is because of the super cool `Reinforcement Governer` haha

**Comment by chris-chris** [comment]
I'm going to integrate more chain and harness the rewarding algorithm

**Comment by chris-chris** [comment]
I have so many idea to implement ;) +1

**Pull request merged**
